### ISSUE TITLE
Setup React Native environment

### ISSUE THREAD

**Issue by muhammadnazreen** [t-analog/crowdfinder-client#27]
- [x] Afiq
- [ ] Arif
- [x] Iskandar
- [x] Nazreen
- [x] Fikri

**Comment by mangkoran** [comment]
![image](https://user-images.githubusercontent.com/57625126/142745924-78a43b2d-d9db-445e-8bb2-c36133b8e095.png)

**Comment by mizlqrn00** [comment]
![image](https://user-images.githubusercontent.com/84320653/142746069-05072fb5-b7bb-489a-a164-521a9eb31694.png)

**Comment by mrperfectt** [comment]
![image](https://user-images.githubusercontent.com/77198649/142746384-ee5362a3-bca5-4361-8e20-bcbe520e14f1.png)

**Comment by muhammadnazreen** [comment]
![image](https://user-images.githubusercontent.com/92769168/142746713-f8c42d6b-e02e-419a-92ce-5baa975574d0.png)
